version: '3.1'
services:
  stats-server:
    build: analytics-app
    container_name: analytics
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: analytics-db
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER = ${ANALYTICS_POSTGRES_USER}
      - POSTGRES_PASSWORD = ${ANALYTICS_POSTGRES_PASSWORD}

  ewm-service:
    build: afisha-app
    container_name: afisha
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server

  ewm-db:
    image: postgres:14-alpine
    container_name: afisha-db
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER = ${AFISHA_POSTGRES_USER}
      - POSTGRES_PASSWORD = ${AFISHA_POSTGRES_PASSWORD}
