version: '3.1'
services:
  stats-server:
    build: analytics-app
    container_name: analytics
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/analytics
      - SPRING_DATASOURCE_USERNAME=${ANALYTICS_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${ANALYTICS_POSTGRES_PASSWORD}

  stats-db:
    image: postgres:14-alpine
    container_name: analytics-db
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=${ANALYTICS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ANALYTICS_POSTGRES_PASSWORD}

  ewm-service:
    build: afisha-app
    container_name: afisha
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/afisha
      - SPRING_DATASOURCE_USERNAME=${AFISHA_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${AFISHA_POSTGRES_PASSWORD}

  ewm-db:
    image: postgres:14-alpine
    container_name: afisha-db
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=${AFISHA_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AFISHA_POSTGRES_PASSWORD}
